//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientFormTema2.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ListaParticipantiConsursSoap")]
    public interface ListaParticipantiConsursSoap {
        
        // CODEGEN: Generating message contract since element name GetParticipantsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetParticipants", ReplyAction="*")]
        ClientFormTema2.ServiceReference1.GetParticipantsResponse GetParticipants(ClientFormTema2.ServiceReference1.GetParticipantsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetParticipants", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientFormTema2.ServiceReference1.GetParticipantsResponse> GetParticipantsAsync(ClientFormTema2.ServiceReference1.GetParticipantsRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertParticipants", ReplyAction="*")]
        ClientFormTema2.ServiceReference1.InsertParticipantsResponse InsertParticipants(ClientFormTema2.ServiceReference1.InsertParticipantsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertParticipants", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientFormTema2.ServiceReference1.InsertParticipantsResponse> InsertParticipantsAsync(ClientFormTema2.ServiceReference1.InsertParticipantsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteParticipants", ReplyAction="*")]
        void DeleteParticipants(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteParticipants", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteParticipantsAsync(int id);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditParticipants", ReplyAction="*")]
        ClientFormTema2.ServiceReference1.EditParticipantsResponse EditParticipants(ClientFormTema2.ServiceReference1.EditParticipantsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditParticipants", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientFormTema2.ServiceReference1.EditParticipantsResponse> EditParticipantsAsync(ClientFormTema2.ServiceReference1.EditParticipantsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetParticipantsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetParticipants", Namespace="http://tempuri.org/", Order=0)]
        public ClientFormTema2.ServiceReference1.GetParticipantsRequestBody Body;
        
        public GetParticipantsRequest() {
        }
        
        public GetParticipantsRequest(ClientFormTema2.ServiceReference1.GetParticipantsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetParticipantsRequestBody {
        
        public GetParticipantsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetParticipantsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetParticipantsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientFormTema2.ServiceReference1.GetParticipantsResponseBody Body;
        
        public GetParticipantsResponse() {
        }
        
        public GetParticipantsResponse(ClientFormTema2.ServiceReference1.GetParticipantsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetParticipantsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientFormTema2.ServiceReference1.ArrayOfString GetParticipantsResult;
        
        public GetParticipantsResponseBody() {
        }
        
        public GetParticipantsResponseBody(ClientFormTema2.ServiceReference1.ArrayOfString GetParticipantsResult) {
            this.GetParticipantsResult = GetParticipantsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertParticipantsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertParticipants", Namespace="http://tempuri.org/", Order=0)]
        public ClientFormTema2.ServiceReference1.InsertParticipantsRequestBody Body;
        
        public InsertParticipantsRequest() {
        }
        
        public InsertParticipantsRequest(ClientFormTema2.ServiceReference1.InsertParticipantsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertParticipantsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string adress;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string facebook;
        
        public InsertParticipantsRequestBody() {
        }
        
        public InsertParticipantsRequestBody(int id, string name, string adress, string username, string facebook) {
            this.id = id;
            this.name = name;
            this.adress = adress;
            this.username = username;
            this.facebook = facebook;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertParticipantsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertParticipantsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientFormTema2.ServiceReference1.InsertParticipantsResponseBody Body;
        
        public InsertParticipantsResponse() {
        }
        
        public InsertParticipantsResponse(ClientFormTema2.ServiceReference1.InsertParticipantsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertParticipantsResponseBody {
        
        public InsertParticipantsResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditParticipantsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditParticipants", Namespace="http://tempuri.org/", Order=0)]
        public ClientFormTema2.ServiceReference1.EditParticipantsRequestBody Body;
        
        public EditParticipantsRequest() {
        }
        
        public EditParticipantsRequest(ClientFormTema2.ServiceReference1.EditParticipantsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditParticipantsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string adress;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string facebook;
        
        public EditParticipantsRequestBody() {
        }
        
        public EditParticipantsRequestBody(int id, string name, string adress, string username, string facebook) {
            this.id = id;
            this.name = name;
            this.adress = adress;
            this.username = username;
            this.facebook = facebook;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditParticipantsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditParticipantsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientFormTema2.ServiceReference1.EditParticipantsResponseBody Body;
        
        public EditParticipantsResponse() {
        }
        
        public EditParticipantsResponse(ClientFormTema2.ServiceReference1.EditParticipantsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EditParticipantsResponseBody {
        
        public EditParticipantsResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ListaParticipantiConsursSoapChannel : ClientFormTema2.ServiceReference1.ListaParticipantiConsursSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListaParticipantiConsursSoapClient : System.ServiceModel.ClientBase<ClientFormTema2.ServiceReference1.ListaParticipantiConsursSoap>, ClientFormTema2.ServiceReference1.ListaParticipantiConsursSoap {
        
        public ListaParticipantiConsursSoapClient() {
        }
        
        public ListaParticipantiConsursSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ListaParticipantiConsursSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListaParticipantiConsursSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListaParticipantiConsursSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientFormTema2.ServiceReference1.GetParticipantsResponse ClientFormTema2.ServiceReference1.ListaParticipantiConsursSoap.GetParticipants(ClientFormTema2.ServiceReference1.GetParticipantsRequest request) {
            return base.Channel.GetParticipants(request);
        }
        
        public ClientFormTema2.ServiceReference1.ArrayOfString GetParticipants() {
            ClientFormTema2.ServiceReference1.GetParticipantsRequest inValue = new ClientFormTema2.ServiceReference1.GetParticipantsRequest();
            inValue.Body = new ClientFormTema2.ServiceReference1.GetParticipantsRequestBody();
            ClientFormTema2.ServiceReference1.GetParticipantsResponse retVal = ((ClientFormTema2.ServiceReference1.ListaParticipantiConsursSoap)(this)).GetParticipants(inValue);
            return retVal.Body.GetParticipantsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientFormTema2.ServiceReference1.GetParticipantsResponse> ClientFormTema2.ServiceReference1.ListaParticipantiConsursSoap.GetParticipantsAsync(ClientFormTema2.ServiceReference1.GetParticipantsRequest request) {
            return base.Channel.GetParticipantsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientFormTema2.ServiceReference1.GetParticipantsResponse> GetParticipantsAsync() {
            ClientFormTema2.ServiceReference1.GetParticipantsRequest inValue = new ClientFormTema2.ServiceReference1.GetParticipantsRequest();
            inValue.Body = new ClientFormTema2.ServiceReference1.GetParticipantsRequestBody();
            return ((ClientFormTema2.ServiceReference1.ListaParticipantiConsursSoap)(this)).GetParticipantsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientFormTema2.ServiceReference1.InsertParticipantsResponse ClientFormTema2.ServiceReference1.ListaParticipantiConsursSoap.InsertParticipants(ClientFormTema2.ServiceReference1.InsertParticipantsRequest request) {
            return base.Channel.InsertParticipants(request);
        }
        
        public void InsertParticipants(int id, string name, string adress, string username, string facebook) {
            ClientFormTema2.ServiceReference1.InsertParticipantsRequest inValue = new ClientFormTema2.ServiceReference1.InsertParticipantsRequest();
            inValue.Body = new ClientFormTema2.ServiceReference1.InsertParticipantsRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.adress = adress;
            inValue.Body.username = username;
            inValue.Body.facebook = facebook;
            ClientFormTema2.ServiceReference1.InsertParticipantsResponse retVal = ((ClientFormTema2.ServiceReference1.ListaParticipantiConsursSoap)(this)).InsertParticipants(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientFormTema2.ServiceReference1.InsertParticipantsResponse> ClientFormTema2.ServiceReference1.ListaParticipantiConsursSoap.InsertParticipantsAsync(ClientFormTema2.ServiceReference1.InsertParticipantsRequest request) {
            return base.Channel.InsertParticipantsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientFormTema2.ServiceReference1.InsertParticipantsResponse> InsertParticipantsAsync(int id, string name, string adress, string username, string facebook) {
            ClientFormTema2.ServiceReference1.InsertParticipantsRequest inValue = new ClientFormTema2.ServiceReference1.InsertParticipantsRequest();
            inValue.Body = new ClientFormTema2.ServiceReference1.InsertParticipantsRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.adress = adress;
            inValue.Body.username = username;
            inValue.Body.facebook = facebook;
            return ((ClientFormTema2.ServiceReference1.ListaParticipantiConsursSoap)(this)).InsertParticipantsAsync(inValue);
        }
        
        public void DeleteParticipants(int id) {
            base.Channel.DeleteParticipants(id);
        }
        
        public System.Threading.Tasks.Task DeleteParticipantsAsync(int id) {
            return base.Channel.DeleteParticipantsAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientFormTema2.ServiceReference1.EditParticipantsResponse ClientFormTema2.ServiceReference1.ListaParticipantiConsursSoap.EditParticipants(ClientFormTema2.ServiceReference1.EditParticipantsRequest request) {
            return base.Channel.EditParticipants(request);
        }
        
        public void EditParticipants(int id, string name, string adress, string username, string facebook) {
            ClientFormTema2.ServiceReference1.EditParticipantsRequest inValue = new ClientFormTema2.ServiceReference1.EditParticipantsRequest();
            inValue.Body = new ClientFormTema2.ServiceReference1.EditParticipantsRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.adress = adress;
            inValue.Body.username = username;
            inValue.Body.facebook = facebook;
            ClientFormTema2.ServiceReference1.EditParticipantsResponse retVal = ((ClientFormTema2.ServiceReference1.ListaParticipantiConsursSoap)(this)).EditParticipants(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientFormTema2.ServiceReference1.EditParticipantsResponse> ClientFormTema2.ServiceReference1.ListaParticipantiConsursSoap.EditParticipantsAsync(ClientFormTema2.ServiceReference1.EditParticipantsRequest request) {
            return base.Channel.EditParticipantsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientFormTema2.ServiceReference1.EditParticipantsResponse> EditParticipantsAsync(int id, string name, string adress, string username, string facebook) {
            ClientFormTema2.ServiceReference1.EditParticipantsRequest inValue = new ClientFormTema2.ServiceReference1.EditParticipantsRequest();
            inValue.Body = new ClientFormTema2.ServiceReference1.EditParticipantsRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.adress = adress;
            inValue.Body.username = username;
            inValue.Body.facebook = facebook;
            return ((ClientFormTema2.ServiceReference1.ListaParticipantiConsursSoap)(this)).EditParticipantsAsync(inValue);
        }
    }
}
